title: Shellcodex
description: "Binary Exploitation, Shellcoding, ROP, Assembly, and other Low-Level Shenanigans."
baseurl: ""
url: "https://shell-codex.github.io"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
plugins: []

collections:
  shellcode:
    output: true
    permalink: /shellcode/:path/

permalink: /:categories/:title/
